name: Rust to WASM

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'src/**'
      - '**.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'src/**'
      - '**.yml'

jobs:
  wasm-build:
    name: WASM Build
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 项目
      - name: Check out repository
        uses: actions/checkout@v6

      # 2️⃣ 缓存 Cargo 依赖
      - name: Cache Cargo registry & target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # 3️⃣ 安装 Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # 5️⃣ 安装 wasm-pack
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      # 6️⃣ 编译 Rust → WASM
      - name: Build project as WASM
        run: wasm-pack build --release --target web

      # 7️⃣ 上传生成的 wasm
      - name: Upload WASM artifact
        uses: actions/upload-artifact@v3
        with:
          name: wasm-output
          path: pkg/*.wasm
